

CREATE TABLE Posts (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Caption NVARCHAR(255),
    Url NVARCHAR(255),
    Date DATE NOT NULL,
    [UserId] INT FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE NOT NULL,
    [GroupID] INT FOREIGN KEY REFERENCES [Groups](Id)
    --[UserId] INT FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE NOT NULL
);
GO
CREATE TABLE PostLikes (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    [PostId] INT FOREIGN KEY REFERENCES Posts(Id) ON DELETE CASCADE NOT NULL,
    [UserId] INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
);
GO
CREATE TABLE Comments (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Comment VARCHAR(255),
    Date DATE,
    [Owner] INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE NOT NULL,
    [PostId] INT FOREIGN KEY REFERENCES Posts(Id) NOT NULL,
    [ParentCommentId] INT FOREIGN KEY REFERENCES Comments(Id)
);
GO
CREATE TABLE CommentLikes (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    [CommentId] INT FOREIGN KEY REFERENCES Comments(Id) ON DELETE CASCADE ,
    [UserId] INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE Taggeds (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    PostId INT FOREIGN KEY REFERENCES Posts(Id) ON DELETE CASCADE,
    UserId INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE Notifications (
    Id INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
    Caption NVARCHAR(255),
    Date DATE NOT NULL,
    SenderId INT FOREIGN KEY REFERENCES Users(Id),
    OwnerId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
);
GO
CREATE TABLE Chats (
    Id INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
    FirstUser INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    SecondUser INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE Messages (
    Id INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
    ChatId INT FOREIGN KEY REFERENCES Chats(Id) ON DELETE CASCADE,
    SenderId INT FOREIGN KEY REFERENCES Users(Id),
    ReceiverId INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE Friends (
    Id INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
    FirstUser INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    SecondUser INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE FriendRequests (
    Id INT PRIMARY KEY,
    SenderId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    ReceiverId INT FOREIGN KEY REFERENCES Users(Id)
);
GO
CREATE TABLE Groups (
    Id INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
    Date DATE,
    CreatorId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
);
GO
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    Fullname VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    CoverUrl VARCHAR(255),
    ProfilePhotoUrl VARCHAR(255),
    Birthday DATE NOT NULL,
    Phone VARCHAR(20),
    Gender VARCHAR(10),
    About TEXT,
    LastTimeActive DATE,
    IsOnline BIT

);
GO
CREATE TABLE GroupUsers(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE NOT NULL,
	GroupId INT FOREIGN KEY REFERENCES [Groups](Id) NOT NULL,
)

